#!/usr/bin/env bash
#PBS -N generate_datacube
#PBS -q omp
#PBS -l walltime=14:00:00
#PBS -l mem=320g
#PBS -l ncpus=8
#PBS -o ./output

# cd to the directory you submitted your job
cd ${PBS_O_WORKDIR}

. /appli/anaconda/latest/etc/profile.d/conda.sh

conda activate pangeo-forge-recipes-0.9-env

# core computation
#python generate_aviso_datacube.py --start 2019-01-01 --end 2020-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-2019
#python generate_aviso_datacube.py --start 2015-01-01 --end 2020-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-2015-2019
#python generate_aviso_datacube.py --start 2010-01-01 --end 2020-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-2010-2019
#python generate_aviso_datacube.py --start 2000-01-01 --end 2020-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-2000-2019
#python generate_aviso_datacube.py --start 1993-01-01 --end 2023-06-07 --output-dir /home1/datawork/gcaer/data/aviso/datacube-all
#python generate_aviso_datacube.py --start 1993-01-01 --end 2023-06-07 --output-dir /home1/datawork/gcaer/data/aviso/datacube

# AVISO
python generate_aviso_datacube.py --start 2000-01-01 --end 2001-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-1
python generate_aviso_datacube.py --start 2000-01-01 --end 2002-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-2
python generate_aviso_datacube.py --start 2000-01-01 --end 2005-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-5
python generate_aviso_datacube.py --start 2000-01-01 --end 2010-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-10
python generate_aviso_datacube.py --start 2000-01-01 --end 2020-01-01 --output-dir /home1/datawork/gcaer/data/aviso/datacube-20

# ERASTAR